### ISSUE TITLE
Error building pycddlib from source on Windows 11 with Python 3.13.0

### ISSUE THREAD

**Issue by bobmyhill** [mcmtroffaes/pycddlib-standalone#1]
I think this is the same problem as reported here for pycddlib: https://github.com/mcmtroffaes/pycddlib/issues/76

As reported for here for pycddlib-standalone: https://github.com/geodynamics/burnman/issues/610

**Comment by mcmtroffaes** [comment]
Building pycddlib-standalone does require a working compiler. [Quoting the documentation](https://pycddlib.readthedocs.io/en/latest/quickstart.html#standalone):

> You still need a compiler so that Python can compile the extension module

so technically speaking this is an "error" on the user's end for not reading the documentation. But I agree the situation is not ideal. Should wheels be provided on Windows also for the standalone version?

**Comment by bobmyhill** [comment]
I don't think this is necessary for the particular problem raised in https://github.com/geodynamics/burnman/issues/610; if the user is able to install and use a compiler they can also install pycddlib. The bigger issue is that a lot of users aren't going to be able to obtain a working compiler (for one reason or another).

For now, I've released a new version of BurnMan that makes pycddlib optional again. It's not ideal, but we already do the same thing with autograd and numba, so it's not a massive problem.

Thanks!

**Comment by mcmtroffaes** [comment]
Ok! Note that pycddlib should work with no need for a compiler on Windows since wheels are provided. The pycddlib-standalone version is really only meant for environments such as google colab, that have a compiler, but can't handle binary dependencies otherwise. Normally packages should depend on pycddlib and not on pycddlib-standalone. But if there's a good use for pycddlib-standalone that would be helped by providing a binary wheel, I'd definitely consider it. Nevertheless, I want to discourage its use except for when no other option is available such as on google colab.

I'll close this for now.

**Comment by bobmyhill** [comment]
Thanks for the info @mcmtroffaes. 

I wanted to make my code usable within colab (I use colab for teaching classes or for quick collaboration); hence the use of standalone. 

Now that I've made pycddlib optional, I can just ask the user to install pycddlib and fall back to standalone if they want to use colab.

**Comment by mcmtroffaes** [comment]
Thanks for letting me know. My colleague @alessandroantonucci suggested me to create this version of pycddlib that would work on google colab, so I'm really pleased to hear that it is finding more widespread use.

But indeed, dependency management needs some extra thinking when doing this... Ideally the pyproject file would support a flag that one could switch between pycddlib and pycddlib-standalone but I don't think that's possible. Your solution seems reasonable, but I'm open to suggestions to improve the user experience.

**Comment by bobmyhill** [comment]
I don't have any ideas that I'm certain would work, but I wonder whether pycddlib's pyproject.toml could handle the extra dependencies of the default installation so that the user could use `python -m pip install pycddlib[standalone]`.

**Comment by mcmtroffaes** [comment]
Well...

1. The standalone version has *fewer* dependencies, so "standalone" as optional dependency to remove a dependency on gmp/cddlib seems a bit strange.
2. But something like pycddlib[gmp] to make the gmp module optional would make sense. However, the build process is very different between the standalone and regular versions: pycddlib-standalone compiles both cddlib and the extension module (so cddlib is baked into the extension module), whilst pycddlib compliles the extension against the cddlib provided by the system (which is much cleaner). Since pycddlib already requires a binary cddlib library to be present, there's currently no option to install ``cdd.gmp`` separately from ``cdd``, as the benefit isn't that big, and it wouldn't enable a "standalone" version.

So, the story is more complicated than providing gmp as an optional dependency to permit Google Colab to use pycddlib... The problem with Google Colab is that it really only provides a compiler and no way to specify binary dependencies. So I've opted for a separate package to allow for this unusual but useful scenario.

**Comment by bobmyhill** [comment]
Thanks for the info!

I agree that implementing something like `pip install pycddlib[standalone]` would be unusual; it was just the only way I could think of to maintain a single project with the full installation as default. And allowing `pip install pycddlib[gmp]` would perhaps not be a great plan if you recommend that users use gmp wherever possible.

FWIW, I'm perfectly happy with the setup as it is - a couple of importlib calls within try:except blocks is all I needed to set up the fallbacks for the users of BurnMan who are even less computer savvy than me.

**Comment by mcmtroffaes** [comment]
Ok, thank you for the feedback. Implementing it through a fallback seems like a sensible thing to do.

FWIW I'm not entirely happy with my current solution :sweat_smile: but for now it's the best I could come up with. Thank you for helping to brainstorm around this.
